import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" async />
      </head>

      <body className={`${inter.className} body sm:hidden`}>{children}</body>
    </html>
  );
}

